mautrix/go

crypto/machine_test.go
crypto/store.go
crypto/store_test.go
go.mod
go.sum

* Add tests for the functionality of the Gob and SQL crypto stores
* Change `RemoveOutboundGroupSession` in the Gob store to not check if a session is shared, to be consistent with the SQL store
* Add a test for the functionality of `OlmMachine`, creating an olm and megolm session, sharing the megolm session and encrypting a message

Crypto store and olm machine tests

---

crypto/sql_store.go
crypto/store_test.go

Signed-off-by: Nikos Filippakis <me@nfil.dev>

Add an account ID to crypto tables to differentiate between devices

---

crypto/decryptmegolm.go
crypto/encryptmegolm.go
crypto/machine.go
crypto/machine_test.go
crypto/sessions.go
crypto/sql_store.go
crypto/store_test.go

Implement some of the TODOs in the code
* Insert devices in batches for SQL store
* Take session rotation config from m.room.encryption message
* Fetch device keys if a device is not present in the crypto store

Todo fixes

---

client.go
requests.go
responses.go

https://matrix.org/docs/spec/client_server/r0.6.1#id73
Signed-off-by: David Florness <david@florness.com>

Add client wrapper functions for Device Management endpoints

---

requests.go

https://github.com/matrix-org/matrix-doc/blob/erikj/invite_reject_reasons/proposals/2367-membership-reasons.md
What about 3pid invite?

Add reason-field to some membership requests

---

appservice/message_send_checkpoint.go

Analogous to https://github.com/mautrix/python/pull/75

message send tracking: add UNSUPPORTED and TIMEOUT statuses

---

crypto/canonicaljson/json.go
go.mod
go.sum

Ref: https://github.com/tidwall/gjson/issues/263#issuecomment-1013759340
Modified-by: David Florness <david@florness.com>
Reported-by: rakshazi <osi@rakshazi.me>
Suggested-by: David Florness <david@florness.com>

Upgrade gjson and fix "slice bounds out of range" error

---

client.go
responses.go

This could also be called `GetRoomAliases` but this fit with the rest of the alias functions.

Add GetAliases call to Client

---

.github/workflows/go.yml

ci: update gotestfmt-action from haveyoudebuggedit -> GoTestTools

---

responses.go

Adds knocked rooms to sync response spec.

Add knocked rooms to sync response struct

---

bridge/status/messagecheckpoint.go

message checkpoint step: add function to determine order

---

crypto/machine.go

crypto/machine: fix typo in log

---

bridge/bridge.go

bridge/UpdateBotProfile: set contact info on startup

---

bridge/status/messagecheckpoint.go

checkpoints: add IsValid functions for enums

---

bridge/status/messagecheckpoint.go
event/beeper.go

mss: add delivered_to_users field

---

bridge/bridgeconfig/config.go
bridge/crypto.go
crypto/sql_store.go
crypto/store.go

(keys which lack the metadata about when they're safe to delete)

Add option to delete outdated inbound keys

---

util/dbutil/log.go

dbutil/log: add option to trace log all queries

---

client.go

logging: don't log request start, just log end

---

requests.go

batch send: add forward_if_no_messages field

---

bridge/bridge.go
bridge/matrix.go

MembershipHandlingPortal: add full event to handlers

---

versions.go

versions: add constants for v1.8 and v1.9

---

crypto/devicelist.go
crypto/machine.go

As there's a side effect of going to the crypto store we want the context to at least exist for now.

Add context to OLM machine LoadDevices

---

.pre-commit-config.yaml

pre-commit: specify maunium.net/go/mautrix as local import

---

crypto/keybackup.go

also log the number of imported sessions for fun

base64 encode the session before passing to libolm/goolm

---

event/content.go
event/type.go
event/verification.go

Signed-off-by: saces <saces@c-base.org>

add missing declarations for m.key.verification.ready

---

crypto/machine.go
crypto/sharing.go
crypto/sql_store.go
crypto/sql_store_upgrade/00-latest-revision.sql
crypto/sql_store_upgrade/12-secrets.sql
crypto/store.go
event/content.go
event/encryption.go
event/type.go
id/crypto.go

Secret sharing

---

crypto/keybackup.go

keybackup: skip bad keys in backup instead of erroring

---

crypto/keybackup.go
crypto/store_test.go

There's some clutter here, ignore.

Allow restoring single sessions from backups

---

client.go
crypto/cross_sign_ssss.go
requests.go

Fix endless loop with UI auth causing 401 when uploading keys.

Allow any UI auth for uploading cross signing keys

---

crypto/verificationhelper/reciprocate.go

Remove unnecessary base64 as well.

Use device signing key to verify interactive verification

---

crypto/verificationhelper/doc.go
crypto/verificationhelper/reciprocate.go
crypto/verificationhelper/sas.go
crypto/verificationhelper/verificationhelper.go

I really have no idea what I'm doing. These are just guesses as to what keys I'm supposed to trust and cross-sign.

verificationhelper: actually trust and cross-sign keys

---

.pre-commit-config.yaml
client.go

pre-commit: prevent literal HTTP methods

---

crypto/aescbc/aes_cbc.go
crypto/aescbc/aes_cbc_test.go
crypto/aescbc/errors.go
crypto/backup/encryptedsessiondata.go
crypto/backup/encryptedsessiondata_test.go
crypto/backup/ephemeralkey.go
crypto/backup/ephemeralkey_test.go
crypto/backup/megolmbackup.go
crypto/backup/megolmbackupkey.go
crypto/pkcs7/pkcs7.go
crypto/pkcs7/pkcs7_test.go
crypto/signatures/signatures.go

crypto: add some license headers

---

.github/workflows/go.yml

ci: run tests with goolm as well

---

crypto/keysharing.go

Copies the logic from key import.

Check that shared IGS has higher index than stored

---

crypto/verificationhelper/verificationhelper.go

verificationhelper/StartVerification: actually set devices after FetchKeys

---

crypto/sql_store.go

crypto/sql_store: fix a couple places where the error value is unused

---

crypto/decryptmegolm.go
crypto/keybackup.go
crypto/keyimport.go
crypto/keysharing.go
crypto/machine.go
crypto/machine_test.go
crypto/sql_store.go
crypto/store.go
crypto/store_test.go

crypto/sql_store: add logging on PutGroupSession

---

crypto/encryptmegolm.go

* If getting the devices from the database fails
* If FetchKeys fails
* If createOutboundSessions fails

ShareGroupSession: return error in more cases

---

crypto/verificationhelper/reciprocate.go

verification: check IdentityKey instead of SigningKey in QR mode 2

---

client.go

Enables modifying the request object between retries, eg. to switch contexts after cancel.

Add `UpdateRequestOnRetry` client hook

---

crypto/verificationhelper/verificationhelper.go

verificationhelper: fix sending cancellation to other devices

---

crypto/cross_sign_signing.go

cross signing: don't require master private key to sign master public key

---

crypto/verificationhelper/verificationhelper.go

verificationhelper: don't send cancellation to self

---

crypto/verificationhelper/verificationhelper.go
crypto/verificationhelper/verificationhelper_test.go

verificationhelper: cancel if multiple requests received from same device

---

crypto/verificationhelper/verificationhelper.go

Added 10-minute timeout for verification requests as per
https://spec.matrix.org/v1.10/client-server-api/#error-and-exception-handling

verificationhelper: implement timeout logic

---

client.go

Missed on last PR https://github.com/mautrix/go/pull/241

Add `Client.DefaultHTTPBackoff`

---

bridgev2/bridgeconfig/config.go
bridgev2/bridgeconfig/upgrade.go
bridgev2/matrix/directmedia.go
bridgev2/matrix/mxmain/example-config.yaml

bridgev2/directmedia: add configurable media ID prefix

---

event/audio.go
event/message.go

event: add unstable audio and voice fields

---

crypto/decryptmegolm.go
crypto/verificationhelper/verificationhelper.go

Also made some verification helper interfaces public so that client code can assert type conformance.

decryptmegolm: Use ResolveTrustContext to ensure any DB transactions are carried forward

---

bridgev2/commands/event.go

Matters in a couple of places where we massage the content.

bridgev2: Use pointer type for parsed content in replies

---

crypto/cryptohelper/cryptohelper.go
crypto/decryptmegolm.go
crypto/encryptmegolm.go

This doesn't try to implement the randomized state key, just the scaffolding to encrypt and decrypt state events.

Add rudimentary MSC3414 encrypted state support

---

crypto/backup/encryptedsessiondata.go

crypto/backup: update comment on computing MAC for encrypted session data

---

bridgev2/database/ghost.go

bridgev2/database: allow querying ghosts by metadata

---

bridgev2/bridgeconfig/config.go
bridgev2/messagestatus.go
bridgev2/networkinterface.go
bridgev2/portal.go

Works with my local branch of mautrix-signal.

v2: matrix membership handling

---

client.go
crypto/verificationhelper/reciprocate.go
crypto/verificationhelper/sas.go
crypto/verificationhelper/verificationhelper.go
crypto/verificationhelper/verificationhelper_test.go

verificationhelper: send cancellations to other devices if cancelled from one device

---

bridgev2/commands/startchat.go

bridgev2/commands: fix NPE on search

---

bridgev2/matrix/provisioning.go

bridgev2/provisioning: allow custom auth token retrieval

---

bridge/status/bridgestate.go

bridgestate: deduplicate on remote name

---

bridgev2/matrix/provisioning.go

bridgev2/provisioning: allow custom user ID retrieval

---

bridgev2/matrix/provisioning.go

bridgev2/provisioning: add request ID middleware

---

bridgev2/database/message.go

bridgev2/database: add function to get last N messages in portal

---

crypto/account.go
crypto/goolm/account/account.go
crypto/goolm/account/account_test.go
crypto/goolm/account/register.go
crypto/goolm/crypto/curve25519.go
crypto/goolm/crypto/curve25519_test.go
crypto/goolm/crypto/ed25519.go
crypto/goolm/crypto/ed25519_test.go
crypto/goolm/pk/decryption.go
crypto/goolm/ratchet/olm.go
crypto/goolm/ratchet/olm_test.go
crypto/goolm/session/megolm_outbound_session.go
crypto/goolm/session/megolm_session_test.go
crypto/goolm/session/olm_session.go
crypto/goolm/session/olm_session_test.go
crypto/libolm/account.go
crypto/olm/account.go
crypto/olm/account_test.go
crypto/olm/session_test.go

crypto: always read from crypto/rand

---

bridgev2/simplevent/meta.go

simplevent/meta: add builder pattern methods

---

bridgev2/simplevent/meta.go

simplevent/meta: make builder pattern methods non-pointer receivers

---

.pre-commit-config.yaml
bridge/commands/event.go
bridgev2/commands/event.go
crypto/keysharing.go
crypto/verificationhelper/mockserver_test.go
crypto/verificationhelper/verificationhelper_qr_crosssign_test.go
crypto/verificationhelper/verificationhelper_qr_self_test.go
crypto/verificationhelper/verificationhelper_sas_test.go
crypto/verificationhelper/verificationhelper_test.go

pre-commit: update and ban use of global zerolog logger

---

bridgev2/portal.go

bridgev2/portal: check if client is logged in before handling read receipt

---

crypto/verificationhelper/callbacks_test.go
crypto/verificationhelper/verificationhelper.go
crypto/verificationhelper/verificationhelper_qr_crosssign_test.go
crypto/verificationhelper/verificationhelper_qr_self_test.go
crypto/verificationhelper/verificationhelper_sas_test.go

verificationhelper: add callback for when other user reports done

---

crypto/verificationhelper/ecdhkeys.go
crypto/verificationhelper/ecdhkeys_test.go
crypto/verificationhelper/reciprocate.go
crypto/verificationhelper/sas.go
crypto/verificationhelper/verificationhelper.go
crypto/verificationhelper/verificationhelper_qr_self_test.go
crypto/verificationhelper/verificationhelper_test.go
crypto/verificationhelper/verificationstore.go
crypto/verificationhelper/verificationstore_test.go

verificationhelper: save verification status in store

---

bridgev2/userlogin.go

This allows the caller to block until the cleanup actions are complete.

bridgev2/userlogin: add blocking cleanup delete option

---

bridge/status/bridgestate.go

status/bridgestate: add IsValid function

---

responses.go

See https://github.com/matrix-org/matrix-spec-proposals/pull/3882

responses: add m.get_login_token to capabilities

---

bridge/crypto.go
bridgev2/matrix/crypto.go
filter.go
sync.go

filter: make sub-structs properly nullable so omitempty works

---

client.go
requests.go

Self explanatory. Needed for https://github.com/tulir/gomuks/pull/562.

Support setting status_msg in Client.SetPresence

---

crypto/verificationhelper/callbacks_test.go
crypto/verificationhelper/sas.go
crypto/verificationhelper/verificationhelper.go
crypto/verificationhelper/verificationhelper_sas_test.go
crypto/verificationhelper/verificationhelper_test.go

verificationhelper/sas: include emoji descriptions in callback

---

bridgev2/portal.go

When enabled portal events always block until sent to the queue and will never be dropped.

bridgev2/portal: add blocking queue config

---

bridgev2/portal.go

bridgev2/portal: add function to get per-message profile for sender

---

bridgev2/portal.go

When buffer is disabled, queueEvent will instead acquire a lock and call the handler directly. Hopefully the queueEvent callers are already in a queue and will block so that queueEvent itself doesn't need to be strictly FIFO (if callers aren't in a queue, even the buffered channel writes could race each other).

bridgev2/portal: only use event loop when buffer is enabled

---

bridgev2/bridge.go
bridgev2/matrix/mxmain/main.go
bridgev2/networkinterface.go
bridgev2/portal.go

 bridgev2: add RunOnce method to backfill a single user login and disconnect

---

crypto/verificationhelper/callbacks_test.go
crypto/verificationhelper/verificationhelper.go
crypto/verificationhelper/verificationhelper_test.go

verificationhelper: don't request QR scan if not enabled

---

crypto/verificationhelper/sas.go

verificationhelper/sas: don't trust keys until both MAC events are sent

---

crypto/verificationhelper/sas.go
crypto/verificationhelper/verificationhelper.go
crypto/verificationhelper/verificationhelper_sas_test.go

verificationhelper/sas: fix error when both sides send StartSAS

---

bridgev2/matrix/mxmain/legacymigrate.go

bridgev2/legacymigrate: don't error if post migrate hook fails

---

client.go

Matrix spec specifies POST for v3/delete_devices
https://playground.matrix.org/#post-/_matrix/client/v3/delete_devices

client: fix v3/delete_devices method
